Repository embroider-build/addon-blueprint, pull requests merged in 2022-07, with the labels that each got.

#29 volta pin npm
  package.json
Labels: bug

#30 Provide a fixed root to @babel/eslint-parser
  files/__addonLocation__/.eslintrc.js
Labels: bug

#31 Rebuild on addon changes
  files/test-app-overrides/ember-cli-build.js
Labels: bug

#38 Cleanup unused locals
  index.js
Labels: internal

#40 Switch to pnpm and add tests package
  pnpm-lock.yaml
  pnpm-workspaces.yaml
  tests/package.json
  tests/pnpm-lock.yaml
  yarn.lock
Labels: internal

#43 Fix test-app to not fail prettier linting
  files/test-app-overrides/ember-cli-build.js
Labels: bug

#49 Add Lints
  .eslintignore
  .eslintrc.cjs
  .github/workflows/ci.yml
  index.js
  package.json
  pnpm-lock.yaml
  tests/assertions.ts
  tests/cli.test.ts
  tests/utils.ts
  tests/vite.config.ts
  tests/vitest.config.ts
Labels: internal

#50 Fix test timeouts
  tests/cli.test.ts
  tests/vitest.config.ts
Labels: internal

#51 Use npm package references in docs
  README.md
Labels: documentation

#48 Support ember-cli-update
  README.md
  files/config/ember-cli-update.json
  files/package.json
  index.js
Labels: enhancement

#52 Move .md files to published package
  files/__addonLocation__/.gitignore
  files/__addonLocation__/package.json
  files/__addonLocation__/rollup.config.js
  index.js
  tests/assertions.ts
Labels: enhancement
