Repository embroider-build/addon-blueprint, pull requests merged in 2023-05, with the labels that each got.

#113 Include @babel/runtime in addon devDependencies to fix babel decorator helper transpilation
  files/__addonLocation__/package.json
Labels: bug

#115 Update to Glint 1.0
  files/__addonLocation__/package.json
Labels: enhancement

#116 Update markdown files to match own prettier config
  README.md
  RELEASE.md
  files/CONTRIBUTING.md
  files/README.md
Labels: bug

#117 allowDeclareFields for TS projects, by default
  files/__addonLocation__/babel.config.json
Labels: bug

#119 Upgrade addon dependencies
  files/__addonLocation__/.eslintrc.cjs
  files/__addonLocation__/package.json
Labels: enhancement

#124 pin pnpm to 7 which matches CI, because we support node 14atm, and pn…
  package.json
Labels: internal

#125 Update RELEASE.md
  RELEASE.md
Labels: internal

#127 Updated the addon package's Babel configuration
  files/__addonLocation__/babel.config.json
  files/__addonLocation__/package.json
Labels: bug
