Repository embroider-build/addon-blueprint, pull requests merged in 2023-08, with the labels that each got.

#162 Add docs about things people should know when authoring V2 addons
  AUTHORING_LIBRARIES.md
  files/__addonLocation__/tsconfig.json
  tests/fixtures/explicit-imports/my-addon/src/components/js-component.d.ts
  tests/fixtures/explicit-imports/my-addon/src/components/js-component.hbs
  tests/fixtures/explicit-imports/my-addon/src/components/js-component.js
  tests/fixtures/explicit-imports/my-addon/src/components/nested/index.hbs
  tests/fixtures/explicit-imports/my-addon/src/components/nested/index.js
  tests/fixtures/explicit-imports/my-addon/src/components/template-only.d.ts
  tests/fixtures/explicit-imports/my-addon/src/components/template-only.hbs
  tests/fixtures/explicit-imports/my-addon/src/components/ts-component.hbs
  tests/fixtures/explicit-imports/my-addon/src/components/ts-component.ts
  tests/fixtures/explicit-imports/my-addon/src/index.ts
  tests/fixtures/explicit-imports/my-addon/src/services/my-service.ts
  tests/fixtures/explicit-imports/my-addon/src/template-registry.ts
  tests/fixtures/explicit-imports/my-addon/unpublished-development-types/index.d.ts
  tests/fixtures/explicit-imports/test-app/tests/unit/import-test.ts
  tests/fixtures/explicit-imports/test-app/types/registry.d.ts
  tests/fixtures/typescript-imports/my-addon/src/index.ts
  tests/fixtures/typescript-imports/test-app/tests/unit/import-test.ts
  tests/rollup-build-tests/explicit-imports.test.ts
  tests/rollup-build-tests/typescript-imports/no-components.test.ts
  tests/smoke-tests/--typescript.test.ts
Labels: documentation

#167 Review lint / dotfiles
  files/.prettierignore
  files/__addonLocation__/gitignore
  files/gitignore
  tests/smoke-tests/--addon-only.test.ts
Labels: enhancement

#168 Update addon ignore files
  files/.prettierignore
  files/gitignore
Labels: bug

#171 Update `ember-try` scenarios
  files/.github/workflows/ci.yml
  files/README.md
  files/test-app-overrides/config/ember-try.js
Labels: enhancement

#170 Make sure the addon's `package.json` file is always sorted
  index.js
Labels: enhancement

#169 Make sure the `node_modules` folder is ignored by Git
  files/gitignore
Labels: bug

#173 Improve building the `ember-cli-update` blueprint options
  index.js
Labels: bug

#181 Upgrade eslint-plugin-ember
  files/__addonLocation__/package.json
Labels: enhancement

#177 Upgrade @embroider/test-setup
  additional-test-app-package.json
Labels: enhancement

#182 cjs for all prettier configs
  .prettierrc.cjs
  files/.prettierrc.cjs
  tests/fixtures/default/.prettierrc.cjs
  tests/helpers/assertions.ts
  tests/smoke-tests/within-existing-monorepo/custom-locations.test.ts
  tests/smoke-tests/within-existing-monorepo/defaults.test.ts
Labels: internal

#128 Fix `cd <path>` in CONTRIBUTING.md
  files/CONTRIBUTING.md
  index.js
  src/directory-for-package-name.js
  tests/fixtures/default/CONTRIBUTING.md
  tests/fixtures/pnpm/CONTRIBUTING.md
  tests/fixtures/yarn/CONTRIBUTING.md
  tests/smoke-tests/defaults.test.ts
Labels: bug

#188 pnpm: suggest stricter dep management
  files/.npmrc
  files/__addonLocation__/.npmrc
  index.js
  tests/fixtures/explicit-imports/test-app/tests/unit/import-test.ts
  tests/fixtures/pnpm-addon-only/.npmrc
  tests/fixtures/pnpm/.npmrc
  tests/helpers/utils.ts
  tests/smoke-tests/--addon-only.test.ts
  tests/smoke-tests/defaults.test.ts
  tests/smoke-tests/within-existing-monorepo/defaults.test.ts
Labels: enhancement
