Repository embroider-build/addon-blueprint, pull requests merged in 2023-09, with the labels that each got.

#191 Remove `ember-disable-prototype-extensions` from test app
  additional-test-app-package.json
Labels: enhancement

#201 Use correct extension for Prettier config file in ESLint config
  files/__addonLocation__/.eslintrc.cjs
Labels: bug

#202 Upgrade @typescript-eslint dependencies
  files/__addonLocation__/package.json
Labels: bug

#204 Add workflow_dispatch to ci
  .github/workflows/ci.yml
Labels: internal

#205 local dev: upgrade pnpm so that we have the resolution-mode=highest change
  package.json
Labels: internal

#206 Assure gts works
  AUTHORING_LIBRARIES.md
  files/__addonLocation__/package.json
  files/__addonLocation__/tsconfig.json
  tests/fixtures/typescript/my-addon/src/components/template-only.ts
  tests/helpers/utils.ts
  tests/smoke-tests/--typescript.test.ts
Labels: bug

#209 Better defaults for publicEntrypoints and appReexports
  files/__addonLocation__/rollup.config.mjs
  tests/rollup-build-tests/explicit-imports.test.ts
Labels: enhancement

#210 Add a service usage to the TS tests to help guide our babel config for TS.
  files/__addonLocation__/babel.config.json
  files/__addonLocation__/package.json
  tests/fixtures/typescript/my-addon/src/components/co-located-ts.ts
  tests/fixtures/typescript/my-addon/src/services/example.ts
  tests/smoke-tests/--typescript.test.ts
Labels: bug
