Repository embroider-build/addon-blueprint, pull requests merged in 2023-07, with the labels that each got.

#140 Node 14.19.3 does not exist anymore (sometimes, 500 error from nodejs)
  package.json
Labels: internal

#137 Update for ember-cli `--typescript` changes
  files/test-app-overrides/ember-cli-build.js
Labels: bug

#134 Run tests with latest Ember CLI
  .github/workflows/ci.yml
  index.js
  pnpm-lock.yaml
  tests/cli.test.ts
  tests/package.json
Labels: internal

#129 Skip .gitignore in existing monorepo
  index.js
Labels: bug

#149 Drop node 14 support
  package.json
Labels: breaking

#148 Use a newer pnpm
  .github/actions/pnpm/action.yml
  .github/workflows/ci.yml
  .npmrc
  package.json
  pnpm-lock.yaml
Labels: internal

#147 Reorganize tests in to multiple files so the tests are less overwheming to work with
  files/__addonLocation__/package.json
  tests/cli.test.ts
  tests/smoke-tests/--addon-location.test.ts
  tests/smoke-tests/--addon-only.test.ts
  tests/smoke-tests/--test-app-location.test.ts
  tests/smoke-tests/--typescript.test.ts
  tests/smoke-tests/defaults.test.ts
  tests/smoke-tests/within-existing-monorepo/custom-locations.test.ts
  tests/smoke-tests/within-existing-monorepo/defaults.test.ts
  tests/utils.ts
Labels: internal

#150 Re-enable typescript tests
  .github/workflows/ci.yml
  files/__addonLocation__/package.json
  tests/utils.ts
Labels: internal

#155 Remove node resolve
  files/__addonLocation__/package.json
  files/__addonLocation__/rollup.config.mjs
Labels: bug

#158 Add typescript component building / testing tests
  tests/fixtures/typescript/my-addon/src/components/co-located-ts.hbs
  tests/fixtures/typescript/my-addon/src/components/co-located-ts.ts
  tests/fixtures/typescript/my-addon/src/components/co-located.hbs
  tests/fixtures/typescript/my-addon/src/components/co-located.js
  tests/fixtures/typescript/my-addon/src/components/template-only.hbs
  tests/fixtures/typescript/test-app/tests/rendering/co-located-test.ts
  tests/fixtures/typescript/test-app/tests/rendering/template-only-test.ts
  tests/smoke-tests/--typescript.test.ts
  tests/tsconfig.json
Labels: internal

#146 Add CI workflow to push dist output to separate branch
  files/.github/workflows/push-dist.yml
  tests/fixtures/default/.github/workflows/push-dist.yml
  tests/fixtures/pnpm/.github/workflows/push-dist.yml
  tests/fixtures/yarn/.github/workflows/push-dist.yml
  tests/smoke-tests/defaults.test.ts
Labels: enhancement

#160 Fix TS Imports by recommending folks add the .ts extension to their import paths
  .github/workflows/ci.yml
  files/__addonLocation__/.prettierrc.cjs
  files/__addonLocation__/tsconfig.json
  tests/fixtures/typescript-imports/my-addon/src/index.ts
  tests/fixtures/typescript-imports/my-addon/src/services/my-service.ts
  tests/fixtures/typescript-imports/test-app/tests/unit/import-test.ts
  tests/helpers/meta-helpers.ts
  tests/rollup-build-tests/typescript-imports/no-components.test.ts
  tests/vitest.config.ts
Labels: bug
