Repository embroider-build/addon-blueprint, pull requests merged in 2023-12, with the labels that each got.

#232 Readme: minor formatting fix
  README.md
Labels: documentation

#233 Specify rootDir so that declarations can always be emitted with the correct paths.
  .github/workflows/ci.yml
  files/__addonLocation__/tsconfig.json
  tests/rollup-build-tests/declarations.test.ts
Labels: bug

#234 Setup release plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#235 Dedupe lockfile
  package.json
  pnpm-lock.yaml
Labels: internal

#231 Remove unneeded babel plugins so that shipped addon code is way smaller and easier to debug without sourcemaps
  files/__addonLocation__/babel.config.json
  files/__addonLocation__/package.json
  tests/smoke-tests/--addon-only.test.ts
  tests/smoke-tests/--typescript.test.ts
Labels: enhancement

#227 add quotes around path in GitHub workflow
  files/.github/workflows/push-dist.yml
  tests/fixtures/default/.github/workflows/push-dist.yml
  tests/fixtures/pnpm/.github/workflows/push-dist.yml
  tests/fixtures/yarn/.github/workflows/push-dist.yml
Labels: bug

#222 Use --skip-cleanup for ember-try for faster-exiting try-scenarios
  files/.github/workflows/ci.yml
  tests/fixtures/default/.github/workflows/ci.yml
  tests/fixtures/pnpm/.github/workflows/ci.yml
  tests/fixtures/yarn/.github/workflows/ci.yml
Labels: enhancement

#243 Update dependencies in the addon's package.json
  files/__addonLocation__/package.json
  tests/helpers/utils.ts
  tests/smoke-tests/--typescript.test.ts
Labels: enhancement
