Repository embroider-build/addon-blueprint, pull requests merged in 2024-04, with the labels that each got.

#280 Make sure to use the correct package manager in concurrently scripts
  files/__addonLocation__/package.json
  src/root-package-json.js
Labels: enhancement

#278 fix: update prepack hook to account for ts scenario
  files/__addonLocation__/package.json
Labels: bug

#282 Upgrade the build dependencies in the addon's package.json
  files/__addonLocation__/package.json
Labels: enhancement

#285 docs: update install instructions to use pnpm and remove `skip-npm`
  README.md
Labels: documentation

#284 Update the linting packages and the eslint config
  files/__addonLocation__/.eslintrc.cjs
  files/__addonLocation__/package.json
Labels: enhancement
