Repository embroider-build/addon-blueprint, pull requests merged in 2024-02, with the labels that each got.

#253 Update LTS scenarios
  files/.github/workflows/ci.yml
  files/README.md
  files/test-app-overrides/config/ember-try.js
  tests/fixtures/default/.github/workflows/ci.yml
  tests/fixtures/pnpm/.github/workflows/ci.yml
  tests/fixtures/yarn/.github/workflows/ci.yml
Labels: enhancement

#256 Add missing .gitignores to better support --addon-only scenarios (no test app)
  files/__addonLocation__/gitignore
  tests/smoke-tests/--typescript.test.ts
Labels: bug

#247 fix indentation in GitHub CI workflow
  files/.github/workflows/ci.yml
  tests/fixtures/default/.github/workflows/ci.yml
  tests/fixtures/pnpm/.github/workflows/ci.yml
  tests/fixtures/yarn/.github/workflows/ci.yml
Labels: bug

#260 update release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#262 fix workspace definition
  pnpm-workspace.yaml
Labels: internal

#263 Document typescript option
  README.md
Labels: documentation

#265 Add @glint/core to root package.json
  files/package.json
Labels: bug
