Repository embroider-build/addon-blueprint, pull requests merged in 2025-01, with the labels that each got.

#313 Bump pnpm/action-setup to v4
  .github/workflows/ci.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  files/.github/workflows/ci.yml
  files/.github/workflows/push-dist.yml
  tests/fixtures/pnpm/.github/workflows/ci.yml
  tests/fixtures/pnpm/.github/workflows/push-dist.yml
Labels: enhancement

#319 Never suggest to use global ember-cli
  README.md
Labels: documentation, enhancement

#322 Drop support for yarn@1, set packageManager field in package.json (pnpm 9.x, npm 11.x)
  .github/workflows/ci.yml
  files/package.json
  index.js
Labels: breaking

#323 Remove release-it
  README.md
  index.js
  package.json
  pnpm-lock.yaml
  src/info.js
Labels: breaking

#320 ember-cli 6.1, eslint 9, eslint flat config, RFC#1055
  .gitignore
  files/__addonLocation__/.eslintignore
  files/__addonLocation__/.eslintrc.cjs
  files/__addonLocation__/_js_eslint.config.mjs
  files/__addonLocation__/_ts_eslint.config.mjs
  files/__addonLocation__/babel.config.json
  files/__addonLocation__/package.json
  files/__addonLocation__/tsconfig.json
  files/test-app-overrides/tsconfig.json
  index.js
  package.json
  pnpm-lock.yaml
  src/root-package-json.js
  tests/fixtures/explicit-imports/test-app/tests/unit/import-test.ts
  tests/fixtures/explicit-imports/test-app/types/registry.d.ts
  tests/helpers/utils.ts
  tests/package.json
  tests/smoke-tests/--addon-only.test.ts
Labels: bug, enhancement
